### PR TITLE
mrc-1870 snake_case to camelCase

### PR DESCRIPTION
**Pull request by hillalex**
update all intervention options so that ids are camelCase

### CODE REVIEW

**Review by richfitz — COMMENTED** [review]
How many of these do you want to fix at once? I still see snake_case in the json for:

* graph_cost_cases_averted_config.json
* intervention_options.json (just `zonal_budget`)
* graph_prevalence_config.json (`x_col`, `y_col`, `id_col`)
* table_cost_config.json
* graph_cost_efficacy_config.json
* table_impact_config.json

Can do these in future PRs or just squash them all now?

**Comment by hillalex** [comment]
> How many of these do you want to fix at once? I still see snake_case in the json for:
> 
> * graph_cost_cases_averted_config.json
> * intervention_options.json (just `zonal_budget`)
> * graph_prevalence_config.json (`x_col`, `y_col`, `id_col`)
> * table_cost_config.json
> * graph_cost_efficacy_config.json
> * table_impact_config.json
> 
> Can do these in future PRs or just squash them all now?

yeah they're everywhere, but the configs all need changes to the vue components, this was just to sort out the settings first!

**Comment by hillalex** [comment]
actually sorry  there are changes in the configs that don't require vue changes, let me do those too here

**Comment by hillalex** [comment]
@richfitz  ok ready for review again

**Review by richfitz — APPROVED** [review]

**Pull request merged**
