### PR TITLE
mrc-1535 Get baseline options

### PR DESCRIPTION
**Pull request by EmmaLRussell**

### CODE REVIEW

**Comment by EmmaLRussell** [comment]
Hm, I think maybe we should be creating all these endpoints with validate=true for that to happen. See https://github.com/reside-ic/pkgapi/blob/af754442fa794ee3fe68e73c06069d314bbcedc8/R/returning.R

@richfitz Is that right?

> Are there any tests that the endpoints conform to the schema? I'm guessing pkgapi does something with the `pkgapi_returning_json` function - does that mean that the endpoints themselves throw an error if the returned data is of the wrong type?

**Comment by hillalex** [comment]
That also seems like a bit of a weird approach to me if correct - I feel like checking the schema belongs in a test rather than in the endpoint itself...

**Comment by EmmaLRussell** [comment]
I guess it maybe belongs in both places. It's a feature of pkgapi to provide internally validated endpoints, but it's still valid for there to be blackbox tests of mintr endpoints which should still work regardless of implementation...

Shall I add a mintr ticket to add tests to validate schema for all endpoints?
 

> That also seems like a bit of a weird approach to me if correct - I feel like checking the schema belongs in a test rather than in the endpoint itself...

**Comment by hillalex** [comment]
> I guess it maybe belongs in both places. It's a feature of pkgapi to provide internally validated endpoints, but it's still valid for there to be blackbox tests of mintr endpoints which should still work regardless of implementation...
> 
> Shall I add a mintr ticket to add tests to validate schema for all endpoints?
> 
> > That also seems like a bit of a weird approach to me if correct - I feel like checking the schema belongs in a test rather than in the endpoint itself...

Sounds good - I feel like explicit tests are needed, like you say to be implementation independent and also because there's no actual way of verifying from mintr that the pkgapi validation is happening (I guess unless you can mock the function that the endpoint actually calls to return something bad)

**Comment by EmmaLRussell** [comment]
Ticket for that: https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-1549

> Sounds good - I feel like explicit tests are needed, like you say to be implementation independent and also because there's no actual way of verifying from mintr that the pkgapi validation is happening (I guess unless you can mock the function that the endpoint actually calls to return something bad)

**Comment by richfitz** [comment]
Sorry missed all of this, and the issue around testing is something that I do have strong feelings about - let's chat about this next week?

**Pull request merged**
