### PR TITLE
mrc-1825: implement real prevelance endpoint

### PR DESCRIPTION
**Pull request by richfitz**
This PR starts getting a "real" data source behind mintr.

* Using a simple key-value store to store and retrieve the data. This really should be the job for something like a SQL db but that will be significantly slower than the approach here unfortunately, and we only ever want the data in the chunks that we've divided them up into here.
* Updates the schema json to match the levels and names used in the data, standardising on camelCase and updating enum values
* Makes the json the source of truth for the enum values and enforce that data conform to that (because the json contains other data in addition, driving the source of truth from the json to the data feels easier)
* Sets up a db for testing

~I have not yet wired up anything to fetch and load the true data, but the scripts here are capable of importing it. I'll address this in a future PR as as we need to store the data somewhere and fetch it during deploy.~

The changes to the json will likely break the frontend

### CODE REVIEW

**Review by EmmaLRussell — COMMENTED** [review]
Looks good to me, as far as I understand it. Yes, pretty sure this will break the front end. Is there going to be a way to spin this up with some test data for development and integration testing?

**Comment by richfitz** [comment]
>  Is there going to be a way to spin this up with some test data for development and integration testing?
Yes, just wondering about the best way to do that. I can certainly wire up bringing it up with dummy data but it's pretty inadequate at the moment (it's just random numbers!). Getting the real data wired in would be not much more work, if that feels more useful.

The downside is that we end up with about 1GB of data on disk when running this. I can move to a really fake db for testing (faster to spin up and less disk used) if that's useful

**Comment by EmmaLRussell** [comment]
Quick dummy data sounds probably more appropriate for development, but might be good to include a test with the real data in the build too. @hillalex what do you think?

> 
> The downside is that we end up with about 1GB of data on disk when running this. I can move to a really fake db for testing (faster to spin up and less disk used) if that's useful

**Comment by hillalex** [comment]
I think totally dummy data as in the tests is absolutely fine for a dev environment. 

This image doesn't run for me at the moment:

```
docker run --rm -p 8888:8888 mrcide/mintr:mrc-1825
...
Error in endpoint_graph_prevalence_data(db) : 
  argument "db" is missing, with no default
Calls: <Anonymous> ... <Anonymous> -> target_graph_prevalence_data -> force
Execution halted
```

**Comment by richfitz** [comment]
Thanks, will fix that and add a test of bringing things up via the container

**Review by EmmaLRussell — COMMENTED** [review]
I tried running up MINT targeting this branch to see what broke and got a few little integration issues:
- MINT has been passing back the whole controls options structure to fetch data rather than mapping to name+values - it makes more sense to do that, so I put in a quick fix for that , but was still getting..
- `Invalid value for 'names(options)':\n - Unexpected: population, metabolic` - population and metabolic are both in the provided baseline options, so not sure why mintr isn't accepting them?
- Would be nice to provide default values for level of resistance, itn usage and estimated spraying coverage. I think there are defaults in there at the moment, but they don't match any of the options? (0 vs 0%)
- When returned, the data still wasn't getting displayed in the graph, but I think that's probably one for us to to fix next week!

**Comment by richfitz** [comment]
> MINT has been passing back the whole controls options structure to fetch data rather than mapping to name+values - it makes more sense to do that, so I put in a quick fix for that , but was still getting..

This one I've ignored; it sounds like you'll change the format?

> Invalid value for 'names(options)':\n - Unexpected: population, metabolic - population and metabolic are both in the provided baseline options, so not sure why mintr isn't accepting them?

These are accepted now

> Would be nice to provide default values for level of resistance, itn usage and estimated spraying coverage. I think there are defaults in there at the moment, but they don't match any of the options? (0 vs 0%)

This has been fixed and a test added to prevent regression

> When returned, the data still wasn't getting displayed in the graph, but I think that's probably one for us to to fix next week!

This is now mrc-1833

**Review by EmmaLRussell — APPROVED** [review]
Looks good, fixes those two issues, and the other two we should fix in the first couple of MINT tickets.

**Pull request merged**
